version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: pip install virtualenv
      - run: virtualenv -p python3 env_task
     
