version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: echo "A first hello"
      - run: jupyter-nbconvert --execute task_1/*.ipynb
    
     
